const fs = require('fs');
const assert = require('assert');
const { JSDOM } = require('jsdom');
const fixture = new JSDOM(fs.readFileSync('tests/dom.html', 'utf8'), { runScripts: 'outside-only' });
fixture.window.eval(fs.readFileSync('dom-patch.js', 'utf8'));
fixture.window.eval([...fixture.window.document.scripts].find(script => !script.src).textContent);
fixture.window.document.querySelector('#run').click();
const result = fixture.window.document.querySelector('#result').textContent;
assert(result.startsWith('PASS:'), result);
fixture.window.close();

// Full application integration, synthetic local storage, no external scripts/network.
const dom = new JSDOM(fs.readFileSync('index.html', 'utf8'), { url: 'https://synthetic.example/', runScripts: 'outside-only', pretendToBeVisual: true });
const w = dom.window;
w.scrollTo = () => {};
for (const file of ['dom-patch.js', 'fluency-engine.js', 'app.js']) w.eval(fs.readFileSync(file, 'utf8'));
const api = w.__OBJETIVOS__;
const d = w.document;
const cards = [...d.querySelectorAll('.task-list .task-card')];
assert(cards.length > 2);
const stableCard = cards[1];
const view = d.querySelector('#viewRoot').firstElementChild;
api.toggleTask(cards[0].dataset.taskId, cards[0].dataset.taskDate);
assert(d.contains(stableCard), 'actual app replaced an untouched task card');
assert(d.querySelector('#viewRoot').firstElementChild === view, 'actual app replaced the whole view');
api.setView('fluency');
d.querySelector('[data-action="fluencyTransfer"]').click();
const input = d.querySelector('#fluencyTransferAnswer');
assert(input, 'transfer practice modal did not open');
input.value = 'Я читаю книгу.';
input.dispatchEvent(new w.Event('input', { bubbles: true }));
assert.strictEqual(api.getState().fluency.transferDraft.answer, input.value, 'draft was not preserved');
const before = JSON.stringify(api.getState().fluency.items.map(item => item.scheduling));
d.querySelector('#transferWithoutHelp').checked = true;
d.querySelector('#fluencyTransferForm').dispatchEvent(new w.Event('submit', { bubbles: true, cancelable: true }));
assert.strictEqual(api.getState().fluency.transferChecks.length, 1, 'attempt was not saved');
assert.strictEqual(JSON.stringify(api.getState().fluency.items.map(item => item.scheduling)), before, 'self-assessment inflated memory score');
assert.strictEqual(api.getState().fluency.transferDraft, null);
assert(!d.querySelector('#fluencyTransferForm'), 'saved modal did not close');
dom.window.close();
console.log(JSON.stringify({ ok: true, domIdentity: true, caretPreservation: true, drawerPreservation: true, taskIntegration: true, transferIntegration: true }));
